### ISSUE TITLE
Preparing slides on data viz with R

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/rbootcamp#2]
@malcolmbarrett it would be great if you could prepare a couple of slides about data visualization in R. The visualization part of the bootcamp should take place on Wednesday 15 of August. Could you take care of that? @meredithfranklin and I were thinking that it would be nice if the talk could include both base R and grid (ggplot2).

That same day I'm planning on talking about functional programming and talking about the final project. So I would say that you can spend about 1 hour talking about viz in R and hopefully 1 other hour dedicated to solving one or two problems about data viz. What do you think?

**Comment by gvegayon** [comment]
Yes, the other material will be posted here, all Rmd files (eventually
either a website or a gitbook). No plans to cover other tidyverse materials.

George G. Vega Yon
+1 (626) 381 8171
https://ggvy.cl

**Comment by malcolmbarrett** [comment]
I'll resist the urge to preach the Tidy Word too much then ;)

I'll also plan on having a corresponding long-form Rmd version that can fit in with the other materials

**Comment by gvegayon** [comment]
Hahaha, Its OK if you want to preach about tidythings. It's just that I
became good at R before all that (so haven't had the need to use tidyverse
that much). Actually, I think it will be good if you show them that as well.


George G. Vega Yon
+1 (626) 381 8171
https://ggvy.cl

**Comment by malcolmbarrett** [comment]
Haha I learned base first, too; I am just a full convert (although I'm sure you agree that they're not really in conflict). If there's flexibility in the schedule, I could also do an Introduction to the Tidyverse session or something, but it's already looking pretty full. If not, I'll give some thought about how to do it with ggplot in a way that's not overwhelming.

**Comment by meredithfranklin** [comment]
I think an intro to ggplot for viz is definitely worth including, even if there's no time for a full tidyverse session!

**Comment by gvegayon** [comment]
This sounds good

>  I'll give some thought about how to do it with ggplot in a way that's not overwhelming.

The way I see it, the most we can get the attendees exposed, the better :). The material will be available for later andddd they can try using those tools during the final project (if they want)
